
--TABELA CLIENTE
DROP TABLE CLIENTE;

CREATE TABLE CLIENTE
(
CODIGO      NUMBER CONSTRAINT PK_CLIENTE PRIMARY KEY,
NOME        VARCHAR2(60) NOT NULL,
RUA         VARCHAR2(80) NOT NULL,
NR          NUMBER(4) NOT NULL,
BAIRRO      VARCHAR2(50) NOT NULL,
COMPLEMENTO VARCHAR2(100),
CIDADE      VARCHAR2(50) NOT NULL,
UF          VARCHAR2(2) NOT NULL,
CEP         VARCHAR2(10) NOT NULL
);

--TABELA FONE_CLEINTE
DROP TABLE FONE_CLIENTE;

CREATE TABLE FONE_CLIENTE
(
NUMERO      VARCHAR2(14),
CODIGO_CLI  NUMBER,
CONSTRAINT PK_FONE_CLIENTE PRIMARY KEY (NUMERO, CODIGO_CLI)
);

ALTER TABLE FONE_CLIENTE
ADD CONSTRAINT FK_FONE_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE(CODIGO);

--TABELA PF
DROP TABLE PF;

CREATE TABLE PF
(
CODIGO_CLI      NUMBER CONSTRAINT PK_CLIENTE_PF PRIMARY KEY,
CNPF            VARCHAR2(14) NOT NULL,
RG              VARCHAR2(10) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL
);

ALTER TABLE PF
ADD CONSTRAINT FK_PF_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE(CODIGO);

CREATE UNIQUE INDEX IND_CNPF_PF ON PF (CODIGO_CLI DESC, CNPF DESC, RG DESC, DATA_NASCIMENTO DESC);

--TABELA PJ
DROP TABLE PJ;

CREATE TABLE PJ
(
CODIGO_CLI      NUMBER CONSTRAINT PK_CLIENTE_PJ PRIMARY KEY,
CNPJ            VARCHAR2(19) NOT NULL,
IE              VARCHAR2(10) NOT NULL,
NOME_FANTASIA   VARCHAR2(60) NOT NULL
);

ALTER TABLE PJ
ADD CONSTRAINT FK_PJ_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE(CODIGO);

CREATE UNIQUE INDEX IND_CNPJ_PJ ON PJ (CODIGO_CLI DESC, CNPJ DESC, IE DESC, NOME_FANTASIA DESC);

--TABELA VENDEDOR
DROP TABLE VENDEDOR;

CREATE TABLE VENDEDOR
(
MATRICULA       NUMBER CONSTRAINT PK_VENDEDOR PRIMARY KEY,
NOME            VARCHAR2(60) NOT NULL,
CNPF            VARCHAR2(14) NOT NULL
);

--TABELA FONE_VENDEDOR
DROP TABLE FONE_VENDEDOR;

CREATE TABLE FONE_VENDEDOR
(
NUMERO          VARCHAR2(14),
MATRICULA_VEN   NUMBER,
CONSTRAINT PK_FONE_VENDEDOR PRIMARY KEY (NUMERO, MATRICULA_VEN)
);

ALTER TABLE FONE_VENDEDOR
ADD CONSTRAINT FK_FONE_VENDEDOR FOREIGN KEY (MATRICULA_VEN) REFERENCES VENDEDOR(MATRICULA);

--TABELA PRODUTO
DROP TABLE PRODUTO;

CREATE TABLE PRODUTO
(
CODIGO          NUMBER CONSTRAINT PK_PRODUTO PRIMARY KEY,
DESCRICAO       VARCHAR2(80) NOT NULL,
UNID_MEDIDA     VARCHAR2(10) NOT NULL
);

--TABELA PRATELEIRA
DROP TABLE PRATELEIRA;

CREATE TABLE PRATELEIRA
(
CODIGO          NUMBER(3) CONSTRAINT PK_PRATELEIRA PRIMARY KEY,
DESCRICAO       VARCHAR2(50) NOT NULL,
NUMERO_SECOES   NUMBER(2) NOT NULL
);

--TABELA PEDIDO
DROP TABLE PEDIDO;

CREATE TABLE PEDIDO
(
NUMERO          NUMBER(6),
DATA            DATE NOT NULL,
PRAZO_ENTREGA   DATE,
RUA             VARCHAR2(80),
NR              NUMBER(4),
BAIRRO          VARCHAR2(50),
COMPLEMENTO     VARCHAR2(100),
CIDADE          VARCHAR2(50),
UF              VARCHAR2(2),
CEP             VARCHAR2(10),
TOTAL_FATURA    NUMBER(8,2),
CODIGO_CLI      NUMBER,
MATRICULA_VEN   NUMBER
);

ALTER TABLE PEDIDO
ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_VENDEDOR FOREIGN KEY (MATRICULA_VEN) REFERENCES VENDEDOR(MATRICULA);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE(CODIGO);

ALTER TABLE PEDIDO
ADD CONSTRAINT CK_NUMERO_PEDIDO CHECK (NUMERO BETWEEN 1 AND 99999); --(NUMERO >= 1 AND NUMERO <= 99999) 

--TABELA ESTOQUE
DROP TABLE ESTOQUE;

CREATE TABLE ESTOQUE
(
DATA_ENTRADA        DATE,
CODIGO_PRO          NUMBER,
CODIGO_PRA          NUMBER(3),
QUANTIDADE          NUMBER(5) NOT NULL,
DATA_VALIDADE       DATE
);

ALTER TABLE ESTOQUE
ADD CONSTRAINT PK_ESTOQUE PRIMARY KEY (DATA_ENTRADA, CODIGO_PRO, CODIGO_PRA);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_EST_PRATELEIRA FOREIGN KEY (CODIGO_PRA) REFERENCES PRATELEIRA(CODIGO);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_EST_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO(CODIGO);

--TABELA CAPACIDADE_ESTOQUE
DROP TABLE CAPACIDADE_ESTOQUE;

CREATE TABLE CAPACIDADE_ESTOQUE
(
CODIGO_PRO      NUMBER,
CODIGO_PRA      NUMBER(3),
QUANTIDADE      NUMBER(5) NOT NULL
);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT PK_CAPACIDADE_ESTOQUE PRIMARY KEY (CODIGO_PRO, CODIGO_PRA);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAP_EST_PRATELEIRA FOREIGN KEY (CODIGO_PRA) REFERENCES PRATELEIRA(CODIGO);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAP_EST_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO(CODIGO);

--TABELA ITEM_PRODUTO
DROP TABLE ITEM_PRODUTO;

CREATE TABLE ITEM_PRODUTO
(
CODIGO_PRO          NUMBER,
NUMERO_PED          NUMBER(6),
QUANTIDADE          NUMBER(5) NOT NULL,
PRECO_UNITARIO      NUMBER(5,2) NOT NULL,
VALOR_ITEM          NUMBER(7,2)
);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY (CODIGO_PRO,NUMERO_PED);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (NUMERO_PED) REFERENCES PEDIDO(NUMERO);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO(CODIGO);

CREATE SEQUENCE SEQ_ITEM_ID INCREMENT BY 2;

COMMENT ON TABLE ITEM_PRODUTO IS 'Tabela de Item_produto';
COMMENT ON COLUMN ITEM_PRODUTO.CODIGO_PRO IS 'Coluna de Código do produto';
COMMENT ON COLUMN ITEM_PRODUTO.NUMERO_PED IS 'Coluna de Número do Produto';
COMMENT ON COLUMN ITEM_PRODUTO.QUANTIDADE IS 'Número de Produtos disponíveis';
COMMENT ON COLUMN ITEM_PRODUTO.PRECO_UNITARIO IS 'Coluna de Preço da unidade de cada produto';
COMMENT ON COLUMN ITEM_PRODUTO.VALOR_ITEM IS 'Coluna de Preço total do item';

--ADICIONANDO CLIENTE DEMO
SELECT *
FROM CLIENTE;

INSERT INTO CLIENTE 
SELECT *
FROM DEMO.CLIENTE;

COMMIT;
ROLLBACK;

-- INSERINDO EM FONE_CLIENTE
INSERT INTO FONE_CLIENTE 
SELECT *
FROM DEMO.FONE_CLIENTE;

SELECT *
FROM FONE_CLIENTE;

DESC FONE_CLIENTE;

INSERT INTO PF
SELECT *
FROM DEMO.PF;

INSERT INTO PJ
SELECT *
FROM DEMO.PJ;

INSERT INTO PEDIDO
SELECT *
FROM DEMO.PEDIDO;

INSERT INTO VENDEDOR
SELECT *
FROM DEMO.VENDEDOR;

INSERT INTO FONE_VENDEDOR
SELECT *
FROM DEMO.FONE_VENDEDOR;

INSERT INTO 
SELECT *
FROM DEMO.PF;

-- 1. Produto 207 para todos os pedidos pares e ano menor 2018, com a quantidade 100 e
-- preço unitário R$ 10.00

INSERT INTO ITEM_PRODUTO (NUMERO_PED, CODIGO_PRO, QUANTIDADE, PRECO_UNITARIO)

SELECT NUMERO,
       207,
       100,
       10.00,
FROM PEDIDO
WHERE MOD(NUMERO,2)=0
    AND TO_CHAR(DATA,'YYYY') < 2018;
    
SELECT *
FROM USER_CONS_COLUMNS 
WHERE TABLE_NAME = 'FONE_CLIENTE';

SELECT *
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'FONE_CLIENTE';

SELECT *
FROM USER_CONS_COLUMNS 
WHERE TABLE_NAME = 'CLIENTE';

DELETE FROM CLIENTE CASCADE CONSTRAINT;